In [3]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

for i in range(len(student1)):
    scores = student1[i] + student2[i]
    print(scores)
    print('==========')

144
170
164
167
177


In [4]:
student1 + student2

[69, 78, 72, 91, 85, 75, 92, 92, 76, 92]

In [2]:
import numpy as np
from numpy import ndarray

student1: ndarray = np.array([69, 78, 72, 91, 85])
student2: ndarray = np.array([75, 92, 92, 76, 92])

# 可以做陣列運算，不須使用for...in
totals: ndarray = student1 + student2
for total in totals:
    print(total)
    print('=======')

144
170
164
167
177


In [3]:
array: ndarray = np.array([[1, 2, 3], [4, 5, 6]])
print(array)
# property
# ndim, shape, size, dtype

print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [10]:
np.random.randint(50, 101, size=(50, 5))

array([[ 56,  99,  76,  50,  67],
       [ 56,  68,  86,  54,  76],
       [ 70,  98,  99,  59,  85],
       [ 56,  74,  66,  76,  81],
       [ 91,  92,  55,  94,  57],
       [ 53,  55,  85,  64,  81],
       [ 96,  75,  61,  99,  53],
       [ 98,  78,  64,  76,  81],
       [ 82,  92,  54,  99,  84],
       [ 59,  71,  59,  87,  99],
       [ 84,  57,  97,  60,  92],
       [ 67,  90,  69,  57,  73],
       [ 73,  52,  55,  96,  97],
       [ 91,  61,  78,  76,  64],
       [ 72,  97,  69,  66,  66],
       [ 68,  50,  82,  90,  64],
       [ 85,  78,  62,  86,  72],
       [ 87,  68,  94,  98,  78],
       [ 57,  64, 100,  99,  64],
       [ 86,  63, 100,  83,  71],
       [ 59,  54,  83,  99,  75],
       [ 64,  83,  86,  99,  81],
       [ 95,  81,  95,  74,  88],
       [ 52,  72,  86,  66,  53],
       [ 96,  78,  65,  70,  69],
       [ 64,  76,  89,  51,  61],
       [ 80,  53,  82,  76,  77],
       [ 98,  57,  77,  52,  98],
       [ 81,  80,  55,  76,  78],
       [ 86,  